[versions]
kotlin = "1.9.24"
compileSdk = "34"
minSdk = "23"
targetSdk = "34"
libraryVersionCode = "4"
libraryVersionName = "1.0.5"

appcompat = "1.1.0"
recyclerview = "1.1.0"
cardview = "1.0.0"
material = "1.1.0"
androidxCore = "1.1.0"
junit = "4.13.2"
espressoCore = "3.5.1"
androidxTestExtJunit = "1.1.5"
robolectric = "4.13"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-core = { group = "androidx.core", name = "core", version.ref = "androidxCore" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-test-espresso-web = { group = "androidx.test.espresso", name = "espresso-web", version.ref = "espressoCore" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExtJunit" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
