package hourglass.github.in.katex;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import katex.hourglass.in.mathlib.MathView;

public class MainActivity extends AppCompatActivity {

    private MathView mathView;
    private String math_formula = "${\rm{Mn}}{{\rm{O}}_{\rm{2}}}$";
    private String question = "This formula $f(x) = x^2$ is an example.";
    private final String question_with_html_tags = getHtmlQuestionText();
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        mathView = (MathView) findViewById(R.id.math_view);
        mathView.setDisplayText(question_with_html_tags);
    }

    private String getHtmlQuestionText(){
      return "<p>\n"
          + "\t<span class=\"note-math-description\">\n"
          + "\t\t<span class=\"katex\">\n"
          + "\t\t\t<span class=\"katex-mathml\">\n"
          + "\t\t\t\t<math>\n"
          + "\t\t\t\t\t<semantics>\n"
          + "\t\t\t\t\t\t<mrow>\n"
          + "\t\t\t\t\t\t\t<mi>x</mi>\n"
          + "\t\t\t\t\t\t\t<mo>=</mo>\n"
          + "\t\t\t\t\t\t\t<mrow>\n"
          + "\t\t\t\t\t\t\t\t<mo fence=\"true\">{</mo>\n"
          + "\t\t\t\t\t\t\t\t<mtable>\n"
          + "\t\t\t\t\t\t\t\t\t<mtr>\n"
          + "\t\t\t\t\t\t\t\t\t\t<mtd>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t<mstyle scriptlevel=\"0\" displaystyle=\"false\">\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t<mi>a</mi>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t</mstyle>\n"
          + "\t\t\t\t\t\t\t\t\t\t</mtd>\n"
          + "\t\t\t\t\t\t\t\t\t\t<mtd>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t<mstyle scriptlevel=\"0\" displaystyle=\"false\">\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t<mrow>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t\t<mtext>if&nbsp;</mtext>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t\t<mi>b</mi>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t</mrow>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t</mstyle>\n"
          + "\t\t\t\t\t\t\t\t\t\t</mtd>\n"
          + "\t\t\t\t\t\t\t\t\t</mtr>\n"
          + "\t\t\t\t\t\t\t\t\t<mtr>\n"
          + "\t\t\t\t\t\t\t\t\t\t<mtd>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t<mstyle scriptlevel=\"0\" displaystyle=\"false\">\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t<mi>c</mi>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t</mstyle>\n"
          + "\t\t\t\t\t\t\t\t\t\t</mtd>\n"
          + "\t\t\t\t\t\t\t\t\t\t<mtd>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t<mstyle scriptlevel=\"0\" displaystyle=\"false\">\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t<mrow>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t\t<mtext>if&nbsp;</mtext>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t\t<mi>d</mi>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t</mrow>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t</mstyle>\n"
          + "\t\t\t\t\t\t\t\t\t\t</mtd>\n"
          + "\t\t\t\t\t\t\t\t\t</mtr>\n"
          + "\t\t\t\t\t\t\t\t</mtable>\n"
          + "\t\t\t\t\t\t\t</mrow>\n"
          + "\t\t\t\t\t\t</mrow>\n"
          + "\t\t\t\t\t\t<annotation encoding=\"application/x-tex\">$x = \\begin{cases} a &amp;amp;\\text{if } b \\\\ c &amp;amp;\\text{if } d \\end{cases}$</annotation>\n"
          + "\t\t\t\t\t</semantics>\n"
          + "\t\t\t\t</math>\n"
          + "\t\t\t</span>\n"
          + "\t\t\t<span class=\"katex-html\" aria-hidden=\"true\">\n"
          + "\t\t\t\t<span class=\"base\">\n"
          + "\t\t\t\t\t<span class=\"strut\" style=\"height: 0.43056em; vertical-align: 0em;\"></span>\n"
          + "\t\t\t\t\t<span class=\"mord mathdefault\">x</span>\n"
          + "\t\t\t\t\t<span class=\"mspace\" style=\"margin-right: 0.277778em;\"></span>\n"
          + "\t\t\t\t\t<span class=\"mrel\">=</span>\n"
          + "\t\t\t\t\t<span class=\"mspace\" style=\"margin-right: 0.277778em;\"></span>\n"
          + "\t\t\t\t</span>\n"
          + "\t\t\t\t<span class=\"base\">\n"
          + "\t\t\t\t\t<span class=\"strut\" style=\"height: 3.00003em; vertical-align: -1.25003em;\"></span>\n"
          + "\t\t\t\t\t<span class=\"minner\">\n"
          + "\t\t\t\t\t\t<span class=\"mopen delimcenter\" style=\"top: 0em;\">\n"
          + "\t\t\t\t\t\t\t<span class=\"delimsizing size4\">{</span>\n"
          + "\t\t\t\t\t\t</span>\n"
          + "\t\t\t\t\t\t<span class=\"mord\">\n"
          + "\t\t\t\t\t\t\t<span class=\"mtable\">\n"
          + "\t\t\t\t\t\t\t\t<span class=\"col-align-l\">\n"
          + "\t\t\t\t\t\t\t\t\t<span class=\"vlist-t vlist-t2\">\n"
          + "\t\t\t\t\t\t\t\t\t\t<span class=\"vlist-r\">\n"
          + "\t\t\t\t\t\t\t\t\t\t\t<span class=\"vlist\" style=\"height: 1.69em;\">\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"\" style=\"top: -3.69em;\">\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"pstrut\" style=\"height: 3.008em;\"></span>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"mord\">\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"mord mathdefault\">a</span>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t</span>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"\" style=\"top: -2.25em;\">\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"pstrut\" style=\"height: 3.008em;\"></span>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"mord\">\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"mord mathdefault\">c</span>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t</span>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t</span>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t<span class=\"vlist-s\">\u200B</span>\n"
          + "\t\t\t\t\t\t\t\t\t\t</span>\n"
          + "\t\t\t\t\t\t\t\t\t\t<span class=\"vlist-r\">\n"
          + "\t\t\t\t\t\t\t\t\t\t\t<span class=\"vlist\" style=\"height: 1.19em;\">\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"\"></span>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t</span>\n"
          + "\t\t\t\t\t\t\t\t\t\t</span>\n"
          + "\t\t\t\t\t\t\t\t\t</span>\n"
          + "\t\t\t\t\t\t\t\t</span>\n"
          + "\t\t\t\t\t\t\t\t<span class=\"arraycolsep\" style=\"width: 1em;\"></span>\n"
          + "\t\t\t\t\t\t\t\t<span class=\"col-align-l\">\n"
          + "\t\t\t\t\t\t\t\t\t<span class=\"vlist-t vlist-t2\">\n"
          + "\t\t\t\t\t\t\t\t\t\t<span class=\"vlist-r\">\n"
          + "\t\t\t\t\t\t\t\t\t\t\t<span class=\"vlist\" style=\"height: 1.69em;\">\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"\" style=\"top: -3.69em;\">\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"pstrut\" style=\"height: 3.008em;\"></span>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"mord\">\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"mord text\">\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"mord\">if&nbsp;</span>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"mord mathdefault\">b</span>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t</span>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"\" style=\"top: -2.25em;\">\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"pstrut\" style=\"height: 3.008em;\"></span>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"mord\">\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"mord text\">\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"mord\">if&nbsp;</span>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"mord mathdefault\">d</span>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t</span>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t</span>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t<span class=\"vlist-s\">\u200B</span>\n"
          + "\t\t\t\t\t\t\t\t\t\t</span>\n"
          + "\t\t\t\t\t\t\t\t\t\t<span class=\"vlist-r\">\n"
          + "\t\t\t\t\t\t\t\t\t\t\t<span class=\"vlist\" style=\"height: 1.19em;\">\n"
          + "\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"\"></span>\n"
          + "\t\t\t\t\t\t\t\t\t\t\t</span>\n"
          + "\t\t\t\t\t\t\t\t\t\t</span>\n"
          + "\t\t\t\t\t\t\t\t\t</span>\n"
          + "\t\t\t\t\t\t\t\t</span>\n"
          + "\t\t\t\t\t\t\t</span>\n"
          + "\t\t\t\t\t\t</span>\n"
          + "\t\t\t\t\t\t<span class=\"mclose nulldelimiter\"></span>\n"
          + "\t\t\t\t\t</span>\n"
          + "\t\t\t\t</span>\n"
          + "\t\t\t</span>\n"
          + "\t\t</span>\n"
          + "\t\t<span class=\"note-latex-description\" style=\"display: none;\">$x = \\begin{cases} a &amp;\\text{if } b \\\\ c &amp;\\text{if } d \\end{cases}$</span>\n"
          + "\t</span>\n"
          + "\t<br>\n"
          + "\t</p>";
    }
}
